name: Send Redis stream message

on:
  push:
    branches:
      - main

jobs:
  publish-to-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Install redis-tools
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Push empty data field to Redis stream
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: 6379
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          redis-cli -h $REDIS_HOST --user default -p $REDIS_PORT -a $REDIS_PASSWORD \
            XADD "blocks:projects:mainnet" '*' \
            data '{"projects_updated": true}'
